### PR TITLE
preserve data in the browser

### PR DESCRIPTION
**Pull request by jellywiz**
- Implementation the following interactions:
  - When the user changes the content of any input field, the data is saved to the local storage.
  - When the user loads the page, if there is any data in the local storage the input fields are pre-filled with this data.
- Use the following data model:
  - You must create **a single JavaScript object with all the data from the entire form** and save it in local storage. Do not create one local storage entry per input field.

### CODE REVIEW

**Review by GzimAsani — CHANGES_REQUESTED** [review]
### Hello    @jellywiz @SimonGideon     :wave:   
 Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Good job with your javascript, email and name persists reloads as it should  :+1:
 
 ## Required Changes 

- [ ] Email and full-name persist reloads, but the same thing is not happening for the comment, kindly check the code and update it






 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jellywiz** [comment]
Hi @GzimAsani please check it again and when ever you wrote something click somewhere else before reloading and then you can see it works 
in order the saveData() function would work is when ever the user finishes the comment and click somewhere else to be saved

**Comment by GzimAsani** [comment]
> Hi @GzimAsani please check it again and when ever you wrote something click somewhere else before reloading and then you can see it works

Hi @jellywiz, sorry I didn't try to click outside before reloading, so after doing that it works fine. I apologize for not thinking to try that. Kindly ask for another CR so it can be approved

**Comment by jellywiz** [comment]
Thank you very much for your time

**Review by danmainah — APPROVED** [review]
Hi @jellywiz and @SimonGideon , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 

## Highlights
✔️ No linter errors
✔️ Github flow was correctly used
✔️  Good design

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
